// Mocks generated by Mockito 5.4.6 from annotations
// in buy_beacon/test/orchestrators/shopping_orchestrator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i7;

import 'package:buy_beacon/models/product.dart' as _i4;
import 'package:buy_beacon/models/shop_location.dart' as _i5;
import 'package:buy_beacon/repositories/product_repository.dart' as _i2;
import 'package:buy_beacon/services/geofence_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Product>> getAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, []),
            returnValue: _i3.Future<List<_i4.Product>>.value(<_i4.Product>[]),
          )
          as _i3.Future<List<_i4.Product>>);

  @override
  _i3.Future<void> addProduct(_i4.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.ShopLocation>> findShopsForProducts(List<_i4.Product>? products) =>
      (super.noSuchMethod(
            Invocation.method(#findShopsForProducts, [products]),
            returnValue: _i3.Future<List<_i5.ShopLocation>>.value(<_i5.ShopLocation>[]),
          )
          as _i3.Future<List<_i5.ShopLocation>>);
}

/// A class which mocks [GeofenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeofenceService extends _i1.Mock implements _i6.GeofenceService {
  MockGeofenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> get activeGeofenceIdentifiers =>
      (super.noSuchMethod(
            Invocation.getter(#activeGeofenceIdentifiers),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false) as bool);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> addGeofences(List<_i5.ShopLocation>? newLocations) =>
      (super.noSuchMethod(
            Invocation.method(#addGeofences, [newLocations]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
