// Mocks generated by Mockito from annotations
// in buy_beacon/test/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:collection' as _i2;
import 'dart:ui' as _i6;

import 'package:buy_beacon/models/category_option.dart' as _i8;
import 'package:buy_beacon/models/product.dart' as _i5;
import 'package:buy_beacon/orchestrators/shopping_orchestrator.dart' as _i9;
import 'package:buy_beacon/orchestrators/shopping_state.dart' as _i3;
import 'package:buy_beacon/providers/product_provider.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUnmodifiableListView_0<E> extends _i1.SmartFake
    implements _i2.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShoppingState_1 extends _i1.SmartFake implements _i3.ShoppingState {
  _FakeShoppingState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductProvider extends _i1.Mock implements _i4.ProductProvider {
  MockProductProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UnmodifiableListView<_i5.Product> get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: _FakeUnmodifiableListView_0<_i5.Product>(
              this,
              Invocation.getter(#products),
            ),
          )
          as _i2.UnmodifiableListView<_i5.Product>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  set onProductsChanged(_i6.VoidCallback? value) => super.noSuchMethod(
    Invocation.setter(#onProductsChanged, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> loadInitialData() =>
      (super.noSuchMethod(
            Invocation.method(#loadInitialData, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addProduct(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [name]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> lookupCategory(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#lookupCategory, [name]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<List<_i8.CategoryOption>> getCategoryOptions() =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryOptions, []),
            returnValue: _i7.Future<List<_i8.CategoryOption>>.value(
              <_i8.CategoryOption>[],
            ),
          )
          as _i7.Future<List<_i8.CategoryOption>>);

  @override
  _i7.Future<void> addProductWithCategory(String? name, String? category) =>
      (super.noSuchMethod(
            Invocation.method(#addProductWithCategory, [name, category]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ShoppingOrchestrator].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingOrchestrator extends _i1.Mock
    implements _i9.ShoppingOrchestrator {
  MockShoppingOrchestrator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i3.ShoppingState> get onStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onStateChanged),
            returnValue: _i7.Stream<_i3.ShoppingState>.empty(),
          )
          as _i7.Stream<_i3.ShoppingState>);

  @override
  _i3.ShoppingState get currentState =>
      (super.noSuchMethod(
            Invocation.getter(#currentState),
            returnValue: _FakeShoppingState_1(
              this,
              Invocation.getter(#currentState),
            ),
          )
          as _i3.ShoppingState);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
