// Mocks generated by Mockito from annotations
// in buy_beacon/test/services/location_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:tracelet_platform_interface/src/generated/tracelet_api.g.dart'
    as _i4;
import 'package:tracelet_platform_interface/src/tracelet_platform.dart' as _i2;
import 'package:tracelet_platform_interface/src/types/enums.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TraceletPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class GeneratedMockTraceletPlatform extends _i1.Mock
    implements _i2.TraceletPlatform {
  GeneratedMockTraceletPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.TlLocation> get locationEvents =>
      (super.noSuchMethod(
            Invocation.getter(#locationEvents),
            returnValue: _i3.Stream<_i4.TlLocation>.empty(),
          )
          as _i3.Stream<_i4.TlLocation>);

  @override
  _i3.Stream<_i4.TlLocation> get motionChangeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#motionChangeEvents),
            returnValue: _i3.Stream<_i4.TlLocation>.empty(),
          )
          as _i3.Stream<_i4.TlLocation>);

  @override
  _i3.Stream<_i4.TlActivityChangeEvent> get activityChangeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#activityChangeEvents),
            returnValue: _i3.Stream<_i4.TlActivityChangeEvent>.empty(),
          )
          as _i3.Stream<_i4.TlActivityChangeEvent>);

  @override
  _i3.Stream<_i4.TlProviderChangeEvent> get providerChangeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#providerChangeEvents),
            returnValue: _i3.Stream<_i4.TlProviderChangeEvent>.empty(),
          )
          as _i3.Stream<_i4.TlProviderChangeEvent>);

  @override
  _i3.Stream<_i4.TlGeofenceEvent> get geofenceEvents =>
      (super.noSuchMethod(
            Invocation.getter(#geofenceEvents),
            returnValue: _i3.Stream<_i4.TlGeofenceEvent>.empty(),
          )
          as _i3.Stream<_i4.TlGeofenceEvent>);

  @override
  _i3.Stream<_i4.TlGeofencesChangeEvent> get geofencesChangeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#geofencesChangeEvents),
            returnValue: _i3.Stream<_i4.TlGeofencesChangeEvent>.empty(),
          )
          as _i3.Stream<_i4.TlGeofencesChangeEvent>);

  @override
  _i3.Stream<_i4.TlHeartbeatEvent> get heartbeatEvents =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeatEvents),
            returnValue: _i3.Stream<_i4.TlHeartbeatEvent>.empty(),
          )
          as _i3.Stream<_i4.TlHeartbeatEvent>);

  @override
  _i3.Stream<_i4.TlHttpEvent> get httpEvents =>
      (super.noSuchMethod(
            Invocation.getter(#httpEvents),
            returnValue: _i3.Stream<_i4.TlHttpEvent>.empty(),
          )
          as _i3.Stream<_i4.TlHttpEvent>);

  @override
  _i3.Stream<_i4.TlState> get scheduleEvents =>
      (super.noSuchMethod(
            Invocation.getter(#scheduleEvents),
            returnValue: _i3.Stream<_i4.TlState>.empty(),
          )
          as _i3.Stream<_i4.TlState>);

  @override
  _i3.Stream<bool> get powerSaveChangeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#powerSaveChangeEvents),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Stream<_i4.TlConnectivityChangeEvent> get connectivityChangeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityChangeEvents),
            returnValue: _i3.Stream<_i4.TlConnectivityChangeEvent>.empty(),
          )
          as _i3.Stream<_i4.TlConnectivityChangeEvent>);

  @override
  _i3.Stream<bool> get enabledChangeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#enabledChangeEvents),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Stream<String> get notificationActionEvents =>
      (super.noSuchMethod(
            Invocation.getter(#notificationActionEvents),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  _i3.Stream<_i4.TlAuthorizationEvent> get authorizationEvents =>
      (super.noSuchMethod(
            Invocation.getter(#authorizationEvents),
            returnValue: _i3.Stream<_i4.TlAuthorizationEvent>.empty(),
          )
          as _i3.Stream<_i4.TlAuthorizationEvent>);

  @override
  _i3.Stream<_i4.TlLocation> get watchPositionEvents =>
      (super.noSuchMethod(
            Invocation.getter(#watchPositionEvents),
            returnValue: _i3.Stream<_i4.TlLocation>.empty(),
          )
          as _i3.Stream<_i4.TlLocation>);

  @override
  _i3.Stream<_i4.TlDrivingEvent> get drivingEvents =>
      (super.noSuchMethod(
            Invocation.getter(#drivingEvents),
            returnValue: _i3.Stream<_i4.TlDrivingEvent>.empty(),
          )
          as _i3.Stream<_i4.TlDrivingEvent>);

  @override
  _i3.Stream<_i4.TlImpactEvent> get impactEvents =>
      (super.noSuchMethod(
            Invocation.getter(#impactEvents),
            returnValue: _i3.Stream<_i4.TlImpactEvent>.empty(),
          )
          as _i3.Stream<_i4.TlImpactEvent>);

  @override
  _i3.Stream<_i4.TlModeChangeEvent> get modeChangeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#modeChangeEvents),
            returnValue: _i3.Stream<_i4.TlModeChangeEvent>.empty(),
          )
          as _i3.Stream<_i4.TlModeChangeEvent>);

  @override
  _i3.Stream<_i4.TlCrashModelStatusEvent> get crashModelStatusEvents =>
      (super.noSuchMethod(
            Invocation.getter(#crashModelStatusEvents),
            returnValue: _i3.Stream<_i4.TlCrashModelStatusEvent>.empty(),
          )
          as _i3.Stream<_i4.TlCrashModelStatusEvent>);

  @override
  _i3.Stream<_i4.TlSpeedMotionEvent> get motionModeChangeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#motionModeChangeEvents),
            returnValue: _i3.Stream<_i4.TlSpeedMotionEvent>.empty(),
          )
          as _i3.Stream<_i4.TlSpeedMotionEvent>);

  @override
  _i3.Stream<Map<String?, Object?>> get remoteConfigEvents =>
      (super.noSuchMethod(
            Invocation.getter(#remoteConfigEvents),
            returnValue: _i3.Stream<Map<String?, Object?>>.empty(),
          )
          as _i3.Stream<Map<String?, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> ready(_i4.TlConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#ready, [config]),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> startGeofences() =>
      (super.noSuchMethod(
            Invocation.method(#startGeofences, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> startPeriodic() =>
      (super.noSuchMethod(
            Invocation.method(#startPeriodic, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> getState() =>
      (super.noSuchMethod(
            Invocation.method(#getState, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> setConfig(_i4.TlConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#setConfig, [config]),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> reset([_i4.TlConfig? config]) =>
      (super.noSuchMethod(
            Invocation.method(#reset, [config]),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<void> updateNotification() =>
      (super.noSuchMethod(
            Invocation.method(#updateNotification, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, Object?>> getCurrentPosition(
    _i4.TlCurrentPositionOptions? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, [options]),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> getLastKnownLocation([
    _i4.TlCurrentPositionOptions? options,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getLastKnownLocation, [options]),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<int> watchPosition(_i4.TlCurrentPositionOptions? options) =>
      (super.noSuchMethod(
            Invocation.method(#watchPosition, [options]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> stopWatchPosition(int? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#stopWatchPosition, [watchId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> changePace(bool? isMoving) =>
      (super.noSuchMethod(
            Invocation.method(#changePace, [isMoving]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateLocationProviderOptions(
    _i4.TlDesiredAccuracy? desiredAccuracy,
    double? distanceFilter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocationProviderOptions, [
              desiredAccuracy,
              distanceFilter,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> confirmImpact(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#confirmImpact, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> cancelImpact(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelImpact, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<double> getOdometer() =>
      (super.noSuchMethod(
            Invocation.method(#getOdometer, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<Map<String, Object?>> setOdometer(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setOdometer, [value]),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<bool> addGeofence(_i4.TlGeofence? geofence) =>
      (super.noSuchMethod(
            Invocation.method(#addGeofence, [geofence]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> addGeofences(List<_i4.TlGeofence>? geofences) =>
      (super.noSuchMethod(
            Invocation.method(#addGeofences, [geofences]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeGeofence(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#removeGeofence, [identifier]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeGeofences() =>
      (super.noSuchMethod(
            Invocation.method(#removeGeofences, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, Object?>>> getGeofences() =>
      (super.noSuchMethod(
            Invocation.method(#getGeofences, []),
            returnValue: _i3.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<Map<String, Object?>?> getGeofence(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#getGeofence, [identifier]),
            returnValue: _i3.Future<Map<String, Object?>?>.value(),
          )
          as _i3.Future<Map<String, Object?>?>);

  @override
  _i3.Future<bool> geofenceExists(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#geofenceExists, [identifier]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, Object?>>> getLocations([
    Map<String, Object?>? query,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getLocations, [query]),
            returnValue: _i3.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<int> getCount([Map<String, Object?>? query]) =>
      (super.noSuchMethod(
            Invocation.method(#getCount, [query]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> destroyLocations() =>
      (super.noSuchMethod(
            Invocation.method(#destroyLocations, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> destroySyncedLocations() =>
      (super.noSuchMethod(
            Invocation.method(#destroySyncedLocations, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> destroyLocation(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#destroyLocation, [uuid]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> insertLocation(Map<String, Object?>? params) =>
      (super.noSuchMethod(
            Invocation.method(#insertLocation, [params]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#insertLocation, [params]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<Map<String, Object?>>> sync() =>
      (super.noSuchMethod(
            Invocation.method(#sync, []),
            returnValue: _i3.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<bool> setDynamicHeaders(Map<String, String>? headers) =>
      (super.noSuchMethod(
            Invocation.method(#setDynamicHeaders, [headers]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setRouteContext(Map<String, Object?>? context) =>
      (super.noSuchMethod(
            Invocation.method(#setRouteContext, [context]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> clearRouteContext() =>
      (super.noSuchMethod(
            Invocation.method(#clearRouteContext, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> registerHeadlessHeadersCallback(List<int>? callbackIds) =>
      (super.noSuchMethod(
            Invocation.method(#registerHeadlessHeadersCallback, [callbackIds]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> registerHeadlessSyncBodyBuilder(List<int>? callbackIds) =>
      (super.noSuchMethod(
            Invocation.method(#registerHeadlessSyncBodyBuilder, [callbackIds]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isPowerSaveMode() =>
      (super.noSuchMethod(
            Invocation.method(#isPowerSaveMode, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i6.AuthorizationStatus> getLocationAuthorization() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationAuthorization, []),
            returnValue: _i3.Future<_i6.AuthorizationStatus>.value(
              _i6.AuthorizationStatus.notDetermined,
            ),
          )
          as _i3.Future<_i6.AuthorizationStatus>);

  @override
  _i3.Future<_i6.AuthorizationStatus> requestLocationAuthorization() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationAuthorization, []),
            returnValue: _i3.Future<_i6.AuthorizationStatus>.value(
              _i6.AuthorizationStatus.notDetermined,
            ),
          )
          as _i3.Future<_i6.AuthorizationStatus>);

  @override
  _i3.Future<_i6.NotificationAuthorizationStatus>
  getNotificationAuthorization() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationAuthorization, []),
            returnValue: _i3.Future<_i6.NotificationAuthorizationStatus>.value(
              _i6.NotificationAuthorizationStatus.notDetermined,
            ),
          )
          as _i3.Future<_i6.NotificationAuthorizationStatus>);

  @override
  _i3.Future<_i6.NotificationAuthorizationStatus>
  requestNotificationAuthorization() =>
      (super.noSuchMethod(
            Invocation.method(#requestNotificationAuthorization, []),
            returnValue: _i3.Future<_i6.NotificationAuthorizationStatus>.value(
              _i6.NotificationAuthorizationStatus.notDetermined,
            ),
          )
          as _i3.Future<_i6.NotificationAuthorizationStatus>);

  @override
  _i3.Future<bool> canScheduleExactAlarms() =>
      (super.noSuchMethod(
            Invocation.method(#canScheduleExactAlarms, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> openExactAlarmSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openExactAlarmSettings, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i6.MotionAuthorizationStatus> getMotionAuthorization() =>
      (super.noSuchMethod(
            Invocation.method(#getMotionAuthorization, []),
            returnValue: _i3.Future<_i6.MotionAuthorizationStatus>.value(
              _i6.MotionAuthorizationStatus.notDetermined,
            ),
          )
          as _i3.Future<_i6.MotionAuthorizationStatus>);

  @override
  _i3.Future<_i6.MotionAuthorizationStatus> requestMotionAuthorization() =>
      (super.noSuchMethod(
            Invocation.method(#requestMotionAuthorization, []),
            returnValue: _i3.Future<_i6.MotionAuthorizationStatus>.value(
              _i6.MotionAuthorizationStatus.notDetermined,
            ),
          )
          as _i3.Future<_i6.MotionAuthorizationStatus>);

  @override
  _i3.Future<int> requestTemporaryFullAccuracy(String? purpose) =>
      (super.noSuchMethod(
            Invocation.method(#requestTemporaryFullAccuracy, [purpose]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<_i6.FullAccuracyStatus> requestTemporaryFullAccuracyAuthorization(
    String? purpose,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestTemporaryFullAccuracyAuthorization, [
              purpose,
            ]),
            returnValue: _i3.Future<_i6.FullAccuracyStatus>.value(
              _i6.FullAccuracyStatus.full,
            ),
          )
          as _i3.Future<_i6.FullAccuracyStatus>);

  @override
  _i3.Future<Map<String, Object?>> getProviderState() =>
      (super.noSuchMethod(
            Invocation.method(#getProviderState, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> getSensors() =>
      (super.noSuchMethod(
            Invocation.method(#getSensors, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> getDeviceInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceInfo, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<bool> playSound(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#playSound, [name]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isIgnoringBatteryOptimizations() =>
      (super.noSuchMethod(
            Invocation.method(#isIgnoringBatteryOptimizations, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestSettings(String? action) =>
      (super.noSuchMethod(
            Invocation.method(#requestSettings, [action]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> showSettings(String? action) =>
      (super.noSuchMethod(
            Invocation.method(#showSettings, [action]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, Object?>> getSettingsHealth() =>
      (super.noSuchMethod(
            Invocation.method(#getSettingsHealth, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> getForegroundServiceHealth() =>
      (super.noSuchMethod(
            Invocation.method(#getForegroundServiceHealth, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<bool> openOemSettings(String? label) =>
      (super.noSuchMethod(
            Invocation.method(#openOemSettings, [label]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.TlLocationTuning?> getCurrentLocationTuning() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocationTuning, []),
            returnValue: _i3.Future<_i4.TlLocationTuning?>.value(),
          )
          as _i3.Future<_i4.TlLocationTuning?>);

  @override
  _i3.Future<bool> showPowerManager() =>
      (super.noSuchMethod(
            Invocation.method(#showPowerManager, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> startBackgroundTask() =>
      (super.noSuchMethod(
            Invocation.method(#startBackgroundTask, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> stopBackgroundTask(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#stopBackgroundTask, [taskId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<String> getLog([Map<String, Object?>? query]) =>
      (super.noSuchMethod(
            Invocation.method(#getLog, [query]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(this, Invocation.method(#getLog, [query])),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> destroyLog() =>
      (super.noSuchMethod(
            Invocation.method(#destroyLog, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> emailLog(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#emailLog, [email]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> connectCustomSync(String? url, String? jwt) =>
      (super.noSuchMethod(
            Invocation.method(#connectCustomSync, [url, jwt]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.TlTelematicsRecord?>> getTelematicsEvents(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getTelematicsEvents, [limit]),
            returnValue: _i3.Future<List<_i4.TlTelematicsRecord?>>.value(
              <_i4.TlTelematicsRecord?>[],
            ),
          )
          as _i3.Future<List<_i4.TlTelematicsRecord?>>);

  @override
  _i3.Future<bool> destroyTelematicsEvents() =>
      (super.noSuchMethod(
            Invocation.method(#destroyTelematicsEvents, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> simulateTelematicsEvent(
    String? eventType,
    double? severity,
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#simulateTelematicsEvent, [
              eventType,
              severity,
              latitude,
              longitude,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, Object?>> debugRunCrashModelInference(
    double? peakG,
    double? speedKmh,
    bool? crashLike,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#debugRunCrashModelInference, [
              peakG,
              speedKmh,
              crashLike,
            ]),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<List<_i4.TlLogEntry?>> getLogs(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, [limit]),
            returnValue: _i3.Future<List<_i4.TlLogEntry?>>.value(
              <_i4.TlLogEntry?>[],
            ),
          )
          as _i3.Future<List<_i4.TlLogEntry?>>);

  @override
  _i3.Future<void> clearLogs() =>
      (super.noSuchMethod(
            Invocation.method(#clearLogs, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> log(String? level, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#log, [level, message]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, Object?>> startSchedule() =>
      (super.noSuchMethod(
            Invocation.method(#startSchedule, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>> stopSchedule() =>
      (super.noSuchMethod(
            Invocation.method(#stopSchedule, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<bool> registerHeadlessTask(List<int>? callbackIds) =>
      (super.noSuchMethod(
            Invocation.method(#registerHeadlessTask, [callbackIds]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, Object?>> verifyAuditTrail() =>
      (super.noSuchMethod(
            Invocation.method(#verifyAuditTrail, []),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<Map<String, Object?>?> getAuditProof(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#getAuditProof, [uuid]),
            returnValue: _i3.Future<Map<String, Object?>?>.value(),
          )
          as _i3.Future<Map<String, Object?>?>);

  @override
  _i3.Future<bool> addPrivacyZone(Map<String, Object?>? zone) =>
      (super.noSuchMethod(
            Invocation.method(#addPrivacyZone, [zone]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> addPrivacyZones(List<Map<String, Object?>>? zones) =>
      (super.noSuchMethod(
            Invocation.method(#addPrivacyZones, [zones]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> removePrivacyZone(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#removePrivacyZone, [identifier]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> removePrivacyZones() =>
      (super.noSuchMethod(
            Invocation.method(#removePrivacyZones, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, Object?>>> getPrivacyZones() =>
      (super.noSuchMethod(
            Invocation.method(#getPrivacyZones, []),
            returnValue: _i3.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<bool> isDatabaseEncrypted() =>
      (super.noSuchMethod(
            Invocation.method(#isDatabaseEncrypted, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> encryptDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#encryptDatabase, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, Object?>?> getAttestationToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAttestationToken, []),
            returnValue: _i3.Future<Map<String, Object?>?>.value(),
          )
          as _i3.Future<Map<String, Object?>?>);

  @override
  _i3.Future<Map<String, Object?>?> getDeadReckoningState() =>
      (super.noSuchMethod(
            Invocation.method(#getDeadReckoningState, []),
            returnValue: _i3.Future<Map<String, Object?>?>.value(),
          )
          as _i3.Future<Map<String, Object?>?>);

  @override
  _i3.Future<Map<String, Object?>> getCarbonReport([
    Map<String, Object?>? query,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getCarbonReport, [query]),
            returnValue: _i3.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i3.Future<Map<String, Object?>>);
}
